### ISSUE TITLE
Image references missing in the generated report file

### ISSUE THREAD

**Issue by keiji** [reg-viz/reg-actions#109]
Hi,

I've been using version 2 of this Actions to generate a report file and obtained it as an artifact.

When I open the file, the links to the images are missing.

<img width="50%" src="https://github.com/reg-viz/reg-actions/assets/932136/a684ba72-283e-4118-9b27-7bef5493807f" />

The images referred to in the report file are located at a directory named `__reg__`, which seems to be the path used by the actions as a workspace. And, the workspace is not included in the artifacts.

Is there a good way to solve this problem?

One idea I had was to output the report file within the workspace(`__reg__`).

In this way, I think the report file would be included in the artifact uploaded by the actions. However, currently, the output location of the report file is specified as a `report-file-path`, and I can't find a way to include the workspace name in it.

Thank you for your great work!

**Comment by bokuweb** [comment]
@keiji Thanks for your report. Sorry, I'll do some investigation.

**Comment by bokuweb** [comment]
@keiji fixed by #113
