### ISSUE TITLE
Uploaded artifact cannot be downloaded with `actions/download-artifact@v4`

### ISSUE THREAD

**Issue by keiji** [reg-viz/reg-actions#110]
Artifacts uploaded by the current `reg-actions@v2` cannot be downloaded using `actions/download-artifact@v4`. It's necessary to opt for an older version, `actions/download-artifact@v3`.

The likely cause seems to be the use of an outdated version of the toolkit by `actions/artifact`, which `reg-actions` depends on.
https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md#which-versions-of-the-artifacts-packages-are-compatible

I would appreciate it if you could consider updating the version of `actions/artifact` used in `reg-actions`.
https://github.com/reg-viz/reg-actions/blob/8d03dcc8c7393facfc4bbb3e236d6a6d31222750/package.json#L37-L39

The latest version of `actions/artifact` is `2.1.4`.
https://www.npmjs.com/package/@actions/artifact

However, Upgrading the version of `actions/artifact` could be the cause of breaking changes.
It's possible that artifacts which were previously downloadable with `actions/download-artifact@v3` could become inaccessible, so careful consideration is needed before deciding to implement this change in `reg-actions@v2`.

Since processing with `actions/download-artifact@v3` currently poses no issues, I consider this to be of low priority.

**Comment by bokuweb** [comment]
@keiji fixed by #114. Please try later.

**Comment by keiji** [comment]
Thank you! 
Current v2 with `download-artifact@v4` works well!
