### ISSUE TITLE
The `disable-branch` option is not working

### ISSUE THREAD

**Issue by kentem-sh-yoshimura** [reg-viz/reg-actions#111]
Hello.
reg-viz has always helped me!

The `disable-branch` option does not seem to be working

I have checked the source.
`config.ts`
I think you don't need `getInput` before `getBoolInput`?

**Comment by bokuweb** [comment]
@kentem-sh-yoshimura Thanks. fixed by https://github.com/reg-viz/reg-actions/pull/112
