### ISSUE TITLE
[Feature Request] Support images in comment with `disable-branch` set to true

### ISSUE THREAD

**Issue by MoritzWeber0** [reg-viz/reg-actions#154]
To reduce the size of my repositories, I want to disable that images are pushed to the repository by setting `disable-branch` to `true`. Unfortunately, images are no longer displayed in the PR comment anymore with this option (as described in the README). Instead, they could be uploaded as attachments to the comment: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

Another advantage is that the images are not downloaded when the whole repository is cloned.

**Comment by bokuweb** [comment]
@MoritzWeber0  Thank you for your suggestion. If I remember correctly, there was no suitable API for attaching images in comments. Do you know of any good methods?

**Comment by MoritzWeber0** [comment]
> @MoritzWeber0 Thank you for your suggestion. If I remember correctly, there was no suitable API for attaching images in comments. Do you know of any good methods?

I just checked and there really doesn't seem to be a solution. I'll close the issue then.
